name: CI

on:
    pull_request:
        branches:
            - main

jobs:
    tests-package:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Rust tooling
              uses: dtolnay/rust-toolchain@stable
            - name: Test Rust
              run: cargo test

