name: CI

on:
    pull_request:
        branches:
            - main
    merge_group:

jobs:
    tests-package:
        runs-on: ubuntu-latest
        steps:
            - name: Setup
              uses: ./.github/workflows/common.yml
            - name: Test Rust
              run: cargo test

