name: Publist to crates

on:
    release:
        types: [published]

jobs:
    publish-crate:
        runs-on: ubuntu-latest
        environment: production
        strategy:
            matrix:
                package: [youtube-transcript]
        steps:
            - name: Setup
              uses: ./.github/workflows/common.yml
            - name: publish
              run: cargo publish -p ${{ matrix.package }}