name: Release

on:
    push:
        tags:
          - "v*.*.*"

jobs:
    github-artifact:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                package: [youtube-transcript]
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Rust tooling
              uses: dtolnay/rust-toolchain@stable
            - name: Cache rust
              uses: Swatinem/rust-cache@v2
            - name: generate artifacts
              run: cargo build --release
            - name: Release
              uses: softprops/action-gh-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with: 
                files: target/release/youtube-transcript

            
